name: Rails CI/CD

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '3.1' # Adjust as needed

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run tests
      run: bundle exec rails test
